contests:
  - count: 10
    minStrategic: 0.0
    maxStrategic: 1.0
    plurality: true
    approval: false
    irv: false

# each contest will have all of the following candidates
candidates:
  # well-known candidate aligned right
  - minDirection: 45 # degrees (will be converted to radians)
    maxDirection: 135 # degrees (will be converted to radians)
    minDistance: 0.1
    maxDistance: 0.8
    minNotoriety: 0.8
    maxNotoriety: 1.0
  # well-known candidate aligned left
  - minDirection: 225 # degrees (will be converted to radians)
    maxDirection: 315 # degrees (will be converted to radians)
    minDistance: 0.1
    maxDistance: 0.8
    minNotoriety: 0.8
    maxNotoriety: 1.0
  # lesser-known candidate fully random
  - minDirection: 0 # degrees (will be converted to radians)
    maxDirection: 360 # degrees (will be converted to radians)
    minDistance: 0.0
    maxDistance: 1.0
    minNotoriety: 0.1
    maxNotoriety: 0.8
  # lesser-known candidate fully random
  - minDirection: 0 # degrees (will be converted to radians)
    maxDirection: 360 # degrees (will be converted to radians)
    minDistance: 0.0
    maxDistance: 1.0
    minNotoriety: 0.1
    maxNotoriety: 0.8
  # lesser-known candidate fully random
  - minDirection: 0 # degrees (will be converted to radians)
    maxDirection: 360 # degrees (will be converted to radians)
    minDistance: 0.0
    maxDistance: 1.0
    minNotoriety: 0.1
    maxNotoriety: 0.8

# each contest will have voters generated by all of following voter blocks
voters:
  # right-aligned
  - count: 250 # integer
    minDirection: 45 # degrees
    maxDirection: 135 # degrees
    minDistance: 0.0 # float 0.0 to 1.0
    maxDistance: 1.0 # float 0.0 to 1.0
    minInformation: 0.1 # float 0.0 to 1.0
    maxInformation: 0.9 # float 0.0 to 1.0
  # left-aligned
  - count: 250
    minDirection: 225
    maxDirection: 315
    minDistance: 0.0
    maxDistance: 1.0
    minInformation: 0.1
    maxInformation: 0.9
  # random
  - count: 500
    minDirection: 0
    maxDirection: 360
    minDistance: 0.0
    maxDistance: 1.0
    minInformation: 0.1
    maxInformation: 0.9
